import "bootstrap/scss/bootstrap.scss";
import Header from "../component/Header";
import Footer from "../component/Footer";
// import SmoothScroll from "../shared/SmoothScroll";
import "./globals.scss";
import "./responsive.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <SmoothScroll /> */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
